name: build script for clean.c 		

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      # Checkout repository
      - uses: actions/checkout@v4		

      # Build clean.c and run it with redirected input/output
      - name: build clean			
        run: gcc -o clean clean.c; ./clean <wbcd.txt >cleaned_wbcd.txt		

      # Upload cleaned_wbcd.txt as an artifact
      - name: upload binary			
        uses: actions/upload-artifact@v4	
        with:
          name: Cleaned output from the wbcd.txt
          path: ./cleaned_wbcd.txt			

