name: build script for clean.c 		

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      # Checkout repository
      - uses: actions/checkout@v4		

      # Build clean.c 
      - name: build clean utility
        run: make

      # Upload the executable as an artifact
      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: clean-executable
          path: clean      
             
      # Run the Clean utility on wbcd.txt using imputation strategy and capture the output
      - name: Run clean utility
        run: ./clean < wbcd.txt > cleaned_wbcd.txt

      # Run the Clean utility on wbcd.txt with invalid arguments and capture the output
      - name: Run clean utility
        run: ./clean -a < wbcd.txt > cleaned_wbcd_with_invalid_args.txt

      # Run the Clean utility on wbcd.txt with -d flag and capture the output
      - name: Run clean utility
        run: ./clean -d < wbcd.txt > cleaned_wbcd_with_d_flag.txt

      # Upload cleaned_wbcd.txt as an artifact
      - name: upload output file as artifact			
        uses: actions/upload-artifact@v4	
        with:
          name: wbcd output file
          path: cleaned_wbcd.txt			

